version: "3"

services:
  node:
     build: ./backend
     depends_on:
       - sql
     env_file:
       # Make sure to update this to match your project.
        - ./concertcrawl.env
     environment:
        - MYSQL_HOST=sql
     ports:
        - 8080:4200
     volumes:
        - ./backend/src:/home/node/app/src
        - ./backend/utils:/home/node/app/utils/
        - ./backend/tsconfig.json:/home/node/app/tsconfig.json
  app:
    build: app
    depends_on:
      - node
    #    For deploying to server use ports: - 80:80
    #    For deploying on localhost on linux you may need to use ports: - 81:80
    ports:
      - 80:80
  sql:
    build: ./sql
    # Make sure to update this to match your project.
    env_file:
      - ./concertcrawl.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - concertcrawl:/var/lib/mysql
    ports:
      - 33006:3306
volumes:
  concertcrawl: