
version: "3"
services:
  sql:
    build: ./sql
    volumes:
      - concertcrawl:/var/lib/mysql
    env_file:
      - ./concertcrawl.env
    command: --default-authentication-plugin=mysql_native_password
  app:
    build: ./app
    depends_on:
      - node
    ports:
      - 80:80
      - 443:443
    volumes:
#      Uncomment when renewing ssl
#      - ./app/public:/usr/share/nginx/html
      - ./app/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/concertcrawl/etc/letsencrypt/live/concertcrawl.com/fullchain.pem:/etc/letsencrypt/live/concertcrawl.com/fullchain.pem
      - /docker-volumes/concertcrawl/etc/letsencrypt/live/concertcrawl.com/privkey.pem:/etc/letsencrypt/live/concertcrawl.com/privkey.pem
  node:
    build: ./backend
    env_file:
      - concertcrawl.env
    ports:
      - 8080:4200
    user: "node"
    volumes:
      - ./backend/src:/home/node/app/src
      - ./backend/utils:/home/node/app/utils/
      - ./backend/tsconfig.json:/home/node/app/tsconfig.json

volumes:
  concertcrawl: